backend:
  name: github
  repo: VitaSensus/VitaSensus
  branch: main
  auth_scope: repo
  client_id: Ov23lizdsF6qx8j1eTbn

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Страницы"
    files:
      - file: "index.html"
        label: "Главная страница"
        name: "home"
        fields:
          - {label: "Заголовок", name: "hero-title", widget: "string"}
          - {label: "Подзаголовок", name: "hero-subtitle", widget: "string"}
          - {label: "Текст кнопки", name: "hero-cta", widget: "string"}
          - {label: "Философия - Заголовок", name: "philosophy-title", widget: "string"}
          - {label: "Философия - Текст 1", name: "philosophy-text-1", widget: "text"}
          - {label: "Философия - Текст 2", name: "philosophy-text-2", widget: "text"}
          - {label: "Философия - Текст 3", name: "philosophy-text-3", widget: "text"}
          - {label: "О нас - Заголовок", name: "about-title", widget: "string"}
          - {label: "О нас - Текст 1", name: "about-text-1", widget: "text"}
          - {label: "О нас - Текст 2", name: "about-text-2", widget: "text"}

  - name: "products"
    label: "Продукты"
    folder: "content/products"
    create: true
    fields:
      - {label: "Название", name: "name", widget: "string"}
      - {label: "Подзаголовок", name: "subtitle", widget: "string"}
      - {label: "Описание", name: "description", widget: "text"}
      - {label: "Бейдж", name: "badge", widget: "string"}
      - {label: "Изображение", name: "image", widget: "image"}
      - {label: "Особенности", name: "features", widget: "list", fields: [{label: "Текст", name: "text", widget: "string"}]}

  - name: "blog"
    label: "Блог"
    folder: "content/blog"
    create: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Дата", name: "date", widget: "datetime"}
      - {label: "Краткое описание", name: "excerpt", widget: "text"}
      - {label: "Изображение", name: "image", widget: "image"}
      - {label: "Иконка", name: "icon", widget: "string"}
      - {label: "Полный текст", name: "body", widget: "markdown"} 